stages:
  - build

services:
  - postgres:latest
  - docker:dind

variables:
  POSTGRES_DB: movie_provider
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 12345
  DB_URL: jdbc:postgresql://postgres:5432/movie_provider
  DOCKER_HOST: tcp://docker:2375/

maven-build-job:
  stage: build
  image: maven:3-eclipse-temurin-17
  script: mvn clean package -DskipTests
