spring:
  application:
    name: movie_provider
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    initialization-mode: always
    platform: 'postgres'
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

swagger:
  enabled: true
  host: localhost:8080
  path:

security:
  jwtSecret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiration:
    hours: ${JWT_EXPIRATION_HOURS}

