spring:
  application:
    name: movie_provider
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    initialization-mode: always
    platform: 'postgres'
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movie_provider}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}

swagger:
  enabled: true
  host: localhost:8080
  path:

security:
  jwtSecret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5275}
  issuer: ${JWT_ISSUER:MovieProvider}
  expiration:
    hours: ${JWT_EXPIRATION_HOURS:10}

